// LOGIN
export const LOGIN  = 'LOGIN';
export const LOGOUT  = 'LOGOUT';
// REGISTER
export const REGISTER = 'REGISTER'


// POKEMONS
export const POKEMONS = 'LISTAR_POKEMONS'
export const SELECTPOKEMON = 'SELECT_POKEMON'
export const CLEARSEARCH = 'CLEAR_SEARCH'
export const FAVORITES = 'POKEMONS_FAVORITES'
export const ADDPOKEMON = 'ADD_POKEMON'
export const UPDATEPOKEMON = 'UPDATE_POKEMON'
export const DELETEPOKEMON = 'DELETE_POKEMON'
export const ABILITIES = 'ABILITIES'
export const ERROR = 'ERROR'
